name: Ticket availability check

on:
  schedule:
    - cron: "*/1 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - id: run_ticket_check
        name: Run ticket check
        if: ${{ vars.EMAIL_SENT == 'false' }}
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          URL: ${{ secrets.URL }}
          TARGET_DATE: ${{ vars.TARGET_DATE }}
          EMAIL_SENT: ${{ vars.EMAIL_SENT }}
        run: |
          python main.py
          # Set output based on Python exit code
          if [ $? -eq 0 ]; then
            echo "tickets_found=true" >> $GITHUB_OUTPUT
          else
            echo "tickets_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Mark email as sent
        if: ${{ steps.run_ticket_check.outputs.tickets_found == 'true' }}
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/variables/EMAIL_SENT \
            -f value="true"
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}